# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TwineSDK' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!
  
  pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"

  # Pods for TwineSDK

  target 'TwineSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwineSDKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
